name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: argodemo
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/tore_saterdal
        username: "tore_saterdal+actions"
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  update:

    runs-on: ubuntu-latest
    container: quay.io/tore_saterdal/argocli:latest

    steps:
    - name: Update image tag
      run: /usr/local/bin/argocd app set demoapp --helm-set image.tag=${{ github.sha }}  --server argocd.io.elillevik.com --auth-token ${{ secrets.ARGO_TOKEN }} --insecure